export const FEATURED_COMPANIES = [
  { slug: 'stripe', name: 'Stripe', platform: 'lever' },
  { slug: 'coinbase', name: 'Coinbase', platform: 'lever' },
  { slug: 'binance', name: 'Binance', platform: 'lever' },
  { slug: 'notion', name: 'Notion', platform: 'lever' },
  { slug: 'linear', name: 'Linear', platform: 'ashby' },
  { slug: 'figma', name: 'Figma', platform: 'greenhouse' },
  { slug: 'ramp', name: 'Ramp', platform: 'ashby' },
  { slug: 'mercury', name: 'Mercury', platform: 'ashby' },
  { slug: 'brex', name: 'Brex', platform: 'lever' },
  { slug: 'deel', name: 'Deel', platform: 'ashby' },
  { slug: 'retool', name: 'Retool', platform: 'ashby' },
  { slug: 'replit', name: 'Replit', platform: 'ashby' },
  { slug: 'posthog', name: 'PostHog', platform: 'ashby' },
  { slug: 'miro', name: 'Miro', platform: 'greenhouse' },
  { slug: 'webflow', name: 'Webflow', platform: 'greenhouse' },
  { slug: 'canva', name: 'Canva', platform: 'lever' },
  { slug: 'airtable', name: 'Airtable', platform: 'greenhouse' },
  { slug: 'shopify', name: 'Shopify', platform: 'ashby' },
  { slug: 'reddit', name: 'Reddit', platform: 'lever' },
  { slug: 'duolingo', name: 'Duolingo', platform: 'lever' },
] as const;
