import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  BaseEntity,
} from 'typeorm';
import { AccountingCompany } from './accounting-company.entity';
import { User } from '../../../users/entities/user.entity';

/**
 * Tax Type Enum
 *
 * Common Brazilian tax types that companies must pay
 */
export enum TaxType {
  DAS = 'DAS', // Documento de Arrecadação do Simples Nacional
  DARF = 'DARF', // Documento de Arrecadação de Receitas Federais
  GPS = 'GPS', // Guia da Previdência Social
  ISS = 'ISS', // Imposto Sobre Serviços
  ICMS = 'ICMS', // Imposto sobre Circulação de Mercadorias e Serviços
  IRPJ = 'IRPJ', // Imposto de Renda Pessoa Jurídica
  CSLL = 'CSLL', // Contribuição Social sobre o Lucro Líquido
  PIS = 'PIS', // Programa de Integração Social
  COFINS = 'COFINS', // Contribuição para Financiamento da Seguridade Social
  INSS = 'INSS', // Instituto Nacional do Seguro Social
  FGTS = 'FGTS', // Fundo de Garantia do Tempo de Serviço
}

/**
 * Tax Obligation Status Enum
 */
export enum TaxObligationStatus {
  PENDING = 'pending', // Waiting for payment
  PAID = 'paid', // Payment confirmed
  OVERDUE = 'overdue', // Past due date
  CANCELLED = 'cancelled', // Cancelled by accountant
}

/**
 * TaxObligation Entity
 *
 * Represents a tax payment obligation for a company.
 * Generated by accountants and paid by company owners.
 *
 * Features:
 * - Monthly/periodic tax obligations
 * - Multiple tax types support
 * - Payment tracking (barcode, link, confirmation)
 * - Fine and interest calculation for late payments
 * - Status management (pending, paid, overdue, cancelled)
 */
@Entity('tax_obligations')
export class TaxObligation extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'company_id' })
  companyId: string;

  @ManyToOne(() => AccountingCompany, { eager: true })
  @JoinColumn({ name: 'company_id' })
  company: AccountingCompany;

  @Column({ name: 'generated_by_id' })
  generatedById: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'generated_by_id' })
  generatedBy: User;

  @Column({
    type: 'varchar',
    length: 50,
    name: 'tax_type',
  })
  taxType: TaxType;

  @Column({
    type: 'integer',
    name: 'reference_month',
    comment: 'Month of the tax obligation (1-12)',
  })
  referenceMonth: number;

  @Column({
    type: 'integer',
    name: 'reference_year',
    comment: 'Year of the tax obligation (YYYY format)',
  })
  referenceYear: number;

  @Column({
    type: 'varchar',
    length: 255,
    name: 'file_name',
  })
  fileName: string;

  @Column({
    type: 'varchar',
    length: 500,
    name: 'file_path',
  })
  filePath: string;

  @Column({
    type: 'integer',
    name: 'file_size',
    nullable: true,
  })
  fileSize?: number;

  @Column({
    type: 'varchar',
    length: 100,
    name: 'mime_type',
    nullable: true,
  })
  mimeType?: string;

  @Column({ type: 'date', name: 'due_date' })
  dueDate: Date;

  @Column({ type: 'decimal', precision: 15, scale: 2 })
  amount: number;

  @Column({
    type: 'decimal',
    precision: 15,
    scale: 2,
    name: 'fine_amount',
    default: 0,
  })
  fineAmount: number;

  @Column({
    type: 'decimal',
    precision: 15,
    scale: 2,
    name: 'interest_amount',
    default: 0,
  })
  interestAmount: number;

  @Column({
    type: 'decimal',
    precision: 15,
    scale: 2,
    name: 'total_amount',
  })
  totalAmount: number;

  @Column({
    type: 'varchar',
    length: 20,
    default: TaxObligationStatus.PENDING,
  })
  status: TaxObligationStatus;

  @Column({ type: 'varchar', length: 100, nullable: true })
  barcode?: string;

  @Column({ type: 'text', nullable: true, name: 'payment_link' })
  paymentLink?: string;

  @Column({ type: 'text', nullable: true, name: 'document_url' })
  documentUrl?: string;

  @Column({ type: 'timestamp with time zone', nullable: true, name: 'paid_at' })
  paidAt?: Date;

  @Column({
    type: 'decimal',
    precision: 15,
    scale: 2,
    nullable: true,
    name: 'paid_amount',
  })
  paidAmount?: number;

  @Column({ type: 'text', nullable: true, name: 'payment_confirmation' })
  paymentConfirmation?: string;

  @Column({ type: 'text', nullable: true })
  notes?: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp with time zone' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp with time zone' })
  updatedAt: Date;

  // Helper Methods

  /**
   * Check if payment is overdue
   */
  isOverdue(): boolean {
    if (this.status === TaxObligationStatus.PAID) {
      return false;
    }
    return new Date() > new Date(this.dueDate);
  }

  /**
   * Check if payment is paid
   */
  isPaid(): boolean {
    return this.status === TaxObligationStatus.PAID;
  }

  /**
   * Get days until due date (negative if overdue)
   */
  getDaysUntilDue(): number {
    const today = new Date();
    const due = new Date(this.dueDate);
    const diffTime = due.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  }

  /**
   * Get days overdue (0 if not overdue)
   */
  getDaysOverdue(): number {
    if (!this.isOverdue()) {
      return 0;
    }
    return Math.abs(this.getDaysUntilDue());
  }

  /**
   * Format reference month for display
   * (1, 2024) → Janeiro/2024
   */
  getFormattedReferenceMonth(): string {
    const months = [
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro',
    ];
    return `${months[this.referenceMonth - 1]}/${this.referenceYear}`;
  }

  /**
   * Get reference period as string (YYYY-MM format)
   * (1, 2024) → "2024-01"
   */
  getReferencePeriod(): string {
    const monthStr = this.referenceMonth.toString().padStart(2, '0');
    return `${this.referenceYear}-${monthStr}`;
  }

  /**
   * Get status color for UI
   */
  getStatusColor(): string {
    switch (this.status) {
      case TaxObligationStatus.PAID:
        return 'green';
      case TaxObligationStatus.PENDING:
        return this.isOverdue() ? 'red' : 'yellow';
      case TaxObligationStatus.OVERDUE:
        return 'red';
      case TaxObligationStatus.CANCELLED:
        return 'gray';
      default:
        return 'gray';
    }
  }

  /**
   * Get tax type display name in Portuguese
   */
  getTaxTypeDisplayName(): string {
    const names: Record<TaxType, string> = {
      [TaxType.DAS]: 'DAS - Simples Nacional',
      [TaxType.DARF]: 'DARF - Receitas Federais',
      [TaxType.GPS]: 'GPS - Previdência Social',
      [TaxType.ISS]: 'ISS - Imposto Sobre Serviços',
      [TaxType.ICMS]: 'ICMS - Circulação de Mercadorias',
      [TaxType.IRPJ]: 'IRPJ - Imposto de Renda PJ',
      [TaxType.CSLL]: 'CSLL - Contribuição Social',
      [TaxType.PIS]: 'PIS - Programa de Integração Social',
      [TaxType.COFINS]: 'COFINS - Financiamento da Seguridade',
      [TaxType.INSS]: 'INSS - Instituto Nacional do Seguro Social',
      [TaxType.FGTS]: 'FGTS - Fundo de Garantia',
    };
    return names[this.taxType] || this.taxType;
  }

  /**
   * Calculate total amount with fine and interest
   */
  calculateTotalAmount(): number {
    return Number(this.amount) + Number(this.fineAmount) + Number(this.interestAmount);
  }
}
